import { createLightTheme, tokens } from '@fluentui/react-components';

export const customTheme = createLightTheme({
  colorNeutralBackground1: '#ffffff',
  colorNeutralBackground2: '#f8f9fa',
  colorNeutralBackground3: '#e9ecef',
  colorNeutralBackground4: '#dee2e6',
  colorNeutralForeground1: '#212529',
  colorNeutralForeground2: '#6c757d',
  colorNeutralForeground3: '#adb5bd',
  colorNeutralStroke1: '#dee2e6',
  colorNeutralStroke2: '#ced4da',
  colorBrandBackground1: '#007bff',
  colorBrandBackground2: '#e3f2fd',
  colorBrandForeground1: '#0056b3',
  colorBrandStroke1: '#0056b3',
  colorBrandStroke2: '#bbdefb',
  colorStatusSuccessBackground1: '#d4edda',
  colorStatusSuccessForeground1: '#155724',
  colorStatusSuccessBorder1: '#c3e6cb',
  colorStatusDangerBackground1: '#f8d7da',
  colorStatusDangerForeground1: '#721c24',
  spacingHorizontalS: '8px',
  spacingHorizontalM: '16px',
  spacingHorizontalL: '24px',
  spacingHorizontalXL: '32px',
  spacingVerticalXS: '4px',
  spacingVerticalS: '8px',
  spacingVerticalM: '16px',
  spacingVerticalL: '24px',
  spacingVerticalXL: '32px',
  fontSizeBase100: '10px',
  fontSizeBase200: '12px',
  fontSizeBase300: '14px',
  fontSizeBase400: '16px',
  fontSizeBase500: '18px',
  fontSizeBase600: '20px',
  fontWeightMedium: '500',
  fontWeightSemibold: '600',
  borderRadiusMedium: '6px',
  shadow4: '0 2px 4px rgba(0,0,0,0.1)',
  shadow16: '0 4px 8px rgba(0,0,0,0.15)',
});
